// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { TEST_CONFIG } from "./test.config";

// Determine database URL based on environment
const appEnv =
  process.env.APP_ENV ||
  (process.env.NODE_ENV === "test" ? "test" : "development");
const isTest = appEnv === "test";

// Use test database for test environment, otherwise use DATABASE_URL from env
const databaseUrl = isTest
  ? process.env.DATABASE_URL || TEST_CONFIG.DB_URL
  : env("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `bun prisma/seed.ts`,
  },
  datasource: {
    url: databaseUrl,
  },
});
